name: SFP MSS Trading Bot

on:
  schedule:
    - cron: '*/5 * * * *'  # every 5 minutes
  workflow_dispatch:





jobs:


  scan-market:


    runs-on: ubuntu-latest



    steps:



      # Получение кода

      - name: Checkout repository

        uses: actions/checkout@v4





      # Python

      - name: Setup Python

        uses: actions/setup-python@v5

        with:

          python-version: "3.11"





      # Установка библиотек

      - name: Install dependencies

        run: |

          python -m pip install --upgrade pip

          pip install -r requirements.txt





      # Очистка старого кэша Python

      - name: Clear Python cache

        run: |

          find . -name "__pycache__" -type d -exec rm -rf {} +





      # Диагностика файлов

      - name: Debug repository

        run: |

          echo "========== TREE =========="

          find . -maxdepth 3 -type f


          echo ""

          echo "========== INDICATORS FILES =========="

          find . -name "indicators.py"


          echo ""

          echo "========== VOLUME FUNCTION =========="

          grep -R "def volume_confirmation" .





      # Запуск бота

      - name: Run SFP MSS Bot

        env:

          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}

          CHAT_ID: ${{ secrets.CHAT_ID }}


        run:

          python main.py
